---
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
    # better_html_config: .better-html.yml
  ExtraNewline:
    enabled: false

  Rubocop:
    enabled: true
    exclude:
      - "bin/**/*"
      - "db/**/*"
      - "config/**/*"
      - "node_modules/**/*"
      - "script/**/*"
      - "support/**/*"
      - "tmp/**/*"
      - "test/**/*"
      - "vendor/**/*"
    rubocop_config:
      inherit_from:
        - .rubocop.yml


      # ExtraNewline:
      #   Enabled: false
# ---
# EnableDefaultLinters: false
# linters:
#   Rubocop:
#     enabled: true
#     rubocop_config:
#       inherit_from:
#         - .rubocop.yml
#       Layout/InitialIndentation:
#         Enabled: false
#       Layout/TrailingEmptyLines:
#         Enabled: false
#       Layout/TrailingWhitespace:
#         Enabled: false
#       Naming/FileName:
#         Enabled: false
#       Style/FrozenStringLiteralComment:
#         Enabled: false
#       Layout/LineLength:
#         Enabled: false
#       Lint/UselessAssignment:
#         Enabled: false
#       Layout/FirstHashElementIndentation:
#         Enabled: false
